version: "3.9"

services:
  admin:
    build:
      context: ./admin
    container_name: admin
    env_file: ./admin/.env
    environment:
      - AWS_REGION=us-east-1
    ports:
      - "5001:5001"

  requestor:
    build:
      context: ./requestor
    container_name: requestor
    env_file: ./requestor/.env
    environment:
      - AWS_REGION=us-east-1
    ports:
      - "8000:8000"

  worker:
    build:
      context: ./worker
    container_name: worker
    env_file: ./worker/.env
    environment:
      - AWS_REGION=us-east-1
    restart: on-failure
